@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Apr 19 14:27:44 -0400 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim sha256_core_tb_behav -key {Behavioral:sim_1:Functional:sha256_core_tb} -tclbatch sha256_core_tb.tcl -view C:/Users/Paul/Documents/GitHub/Homework/EEL4783/sha256/sha256/sha256_update_tb_behav.wcfg -log simulate.log"
call xsim  sha256_core_tb_behav -key {Behavioral:sim_1:Functional:sha256_core_tb} -tclbatch sha256_core_tb.tcl -view C:/Users/Paul/Documents/GitHub/Homework/EEL4783/sha256/sha256/sha256_update_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
