# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/cpu/cpu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu || ORIG_REF_NAME==cpu} -quiet] -quiet

# IP: bd/cpu/ip/cpu_axi_sha256_0_1/cpu_axi_sha256_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_axi_sha256_0_1 || ORIG_REF_NAME==cpu_axi_sha256_0_1} -quiet] -quiet

# IP: bd/cpu/ip/cpu_microblaze_0_0/cpu_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_microblaze_0_0 || ORIG_REF_NAME==cpu_microblaze_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_dlmb_v10_0/cpu_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_dlmb_v10_0 || ORIG_REF_NAME==cpu_dlmb_v10_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_ilmb_v10_0/cpu_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_ilmb_v10_0 || ORIG_REF_NAME==cpu_ilmb_v10_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_dlmb_bram_if_cntlr_0/cpu_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==cpu_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_ilmb_bram_if_cntlr_0/cpu_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==cpu_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_lmb_bram_0/cpu_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_lmb_bram_0 || ORIG_REF_NAME==cpu_lmb_bram_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_lmb_v10_0/cpu_lmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_lmb_v10_0 || ORIG_REF_NAME==cpu_lmb_v10_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_xbar_0/cpu_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_xbar_0 || ORIG_REF_NAME==cpu_xbar_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_microblaze_0_axi_periph_0/cpu_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_microblaze_0_axi_periph_0 || ORIG_REF_NAME==cpu_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_microblaze_0_axi_intc_0/cpu_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_microblaze_0_axi_intc_0 || ORIG_REF_NAME==cpu_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_microblaze_0_xlconcat_0/cpu_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_microblaze_0_xlconcat_0 || ORIG_REF_NAME==cpu_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_mdm_1_0/cpu_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_mdm_1_0 || ORIG_REF_NAME==cpu_mdm_1_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_clk_wiz_1_0/cpu_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_clk_wiz_1_0 || ORIG_REF_NAME==cpu_clk_wiz_1_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_rst_clk_wiz_1_100M_0/cpu_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==cpu_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_axi_uartlite_0_0/cpu_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_axi_uartlite_0_0 || ORIG_REF_NAME==cpu_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_axi_timer_0_0/cpu_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_axi_timer_0_0 || ORIG_REF_NAME==cpu_axi_timer_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_auto_pc_0/cpu_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_auto_pc_0 || ORIG_REF_NAME==cpu_auto_pc_0} -quiet] -quiet

# XDC: bd/cpu/cpu_ooc.xdc
