# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pins_constr.xdc

# Block Designs: bd/test/test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test || ORIG_REF_NAME==test} -quiet] -quiet

# IP: bd/test/ip/test_microblaze_0_0/test_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_microblaze_0_0 || ORIG_REF_NAME==test_microblaze_0_0} -quiet] -quiet

# IP: bd/test/ip/test_dlmb_v10_0/test_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_dlmb_v10_0 || ORIG_REF_NAME==test_dlmb_v10_0} -quiet] -quiet

# IP: bd/test/ip/test_ilmb_v10_0/test_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_ilmb_v10_0 || ORIG_REF_NAME==test_ilmb_v10_0} -quiet] -quiet

# IP: bd/test/ip/test_dlmb_bram_if_cntlr_0/test_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==test_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/test/ip/test_ilmb_bram_if_cntlr_0/test_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==test_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/test/ip/test_lmb_bram_0/test_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_lmb_bram_0 || ORIG_REF_NAME==test_lmb_bram_0} -quiet] -quiet

# IP: bd/test/ip/test_xbar_0/test_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_xbar_0 || ORIG_REF_NAME==test_xbar_0} -quiet] -quiet

# IP: bd/test/ip/test_microblaze_0_axi_periph_0/test_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_microblaze_0_axi_periph_0 || ORIG_REF_NAME==test_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/test/ip/test_microblaze_0_axi_intc_0/test_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_microblaze_0_axi_intc_0 || ORIG_REF_NAME==test_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/test/ip/test_microblaze_0_xlconcat_0/test_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_microblaze_0_xlconcat_0 || ORIG_REF_NAME==test_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/test/ip/test_mdm_1_0/test_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_mdm_1_0 || ORIG_REF_NAME==test_mdm_1_0} -quiet] -quiet

# IP: bd/test/ip/test_clk_wiz_1_0/test_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_clk_wiz_1_0 || ORIG_REF_NAME==test_clk_wiz_1_0} -quiet] -quiet

# IP: bd/test/ip/test_rst_clk_wiz_1_100M_0/test_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==test_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/test/ip/test_axi_uartlite_0_0/test_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_axi_uartlite_0_0 || ORIG_REF_NAME==test_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/test/ip/test_led_axi_0_0/test_led_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_led_axi_0_0 || ORIG_REF_NAME==test_led_axi_0_0} -quiet] -quiet

# IP: bd/test/ip/test_axi_sha256_0_0/test_axi_sha256_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_axi_sha256_0_0 || ORIG_REF_NAME==test_axi_sha256_0_0} -quiet] -quiet

# IP: bd/test/ip/test_auto_pc_0/test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_auto_pc_0 || ORIG_REF_NAME==test_auto_pc_0} -quiet] -quiet

# XDC: bd/test/test_ooc.xdc
