# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_axi_uartlite_0_0/cpu_axi_uartlite_0_0.xci
# IP: The module: 'cpu_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_axi_uartlite_0_0/cpu_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_axi_uartlite_0_0/cpu_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_axi_uartlite_0_0/cpu_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_axi_uartlite_0_0/cpu_axi_uartlite_0_0.xci
# IP: The module: 'cpu_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_axi_uartlite_0_0/cpu_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_axi_uartlite_0_0/cpu_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_axi_uartlite_0_0/cpu_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
