# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_xbar_0/cpu_xbar_0.xci
# IP: The module: 'cpu_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_xbar_0/cpu_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_xbar_0/cpu_xbar_0.xci
# IP: The module: 'cpu_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/904pa/Documents/Git/sha256/project/sha256_accelerator/sha256_accelerator.srcs/sources_1/bd/cpu/ip/cpu_xbar_0/cpu_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
